---
- hosts: all
  become: yes
  tasks:
    - name: Disable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "0"
        state: present

    - name: Set FORWARD policy to DROP
      iptables:
        chain: FORWARD
        policy: DROP

    - name: Install rkhunter
      apt:
        name: rkhunter
        state: present

    - name: Run rkhunter check
      command: rkhunter --check --skip-keypress

